### ISSUE TITLE
Model not centered at zero phase when gravity darkening is included

### ISSUE THREAD

**Issue by mkherman** [CadenArmstrong/simuTrans#17]
When I include any parameters related to the gravity darkening, the model gets shifted over, so the middle of the transit does not occur at phase=0. Even if I fix gd_beta=0, just leaving other GD-related parameters in the cfg file (like star_f, phi, lambda) still produces the shift. 
![shift_gd_results](https://cloud.githubusercontent.com/assets/16808181/20533294/fea0d0ba-b0aa-11e6-8fd9-e9c911b6b983.png)
The problem isn't due to an incorrect t0 value, since removing all GD-related parameters restores the model to the center. 
![no_gd_results](https://cloud.githubusercontent.com/assets/16808181/20533303/02ff7012-b0ab-11e6-95fe-91c9b4f0ee95.png)
@chelseah

**Comment by chelseah** [comment]
This is fixed in the latest version on my branch. Model not centered at zero is expected signature of gravity darkening, see Barnes (2009) section 4.2 and Figure 8 as an example. The real problem is that the definition of impact parameter b does not match the conventional definition in the case of an oblate star. Fixed.
